name: Request Survey Data as CSV
description: Use this Issue to request survey data in CSV format for a specific data range
title: "Use this Issue to request survey data in CSV format for a specific data range"
labels: ["survey data requested"]
body:
  - type: markdown
    attributes:
      value: "## Please enter a date range"
  - type: input
    id: start-date
    attributes:
      label: "Start date:"
      placeholder: "MM/DD/YYYY"
    validations:
      required: true
  - type: input
    id: end-date
    attributes:
      label: "End date:"
      placeholder: "MM/DD/YYYY"
    validations:
      required: true  


