name: Deploy and Update AWS Resources

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-1

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      actions: write # This is required for setting up the OIDC subject claim
      contents: read # This is required for checking out the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup AWS subject claim
      uses: ./.github/actions/setup-repo-oidc-claim@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::377117578606:role/thedave42-copilot-survey-engine


#    - name: Setup Terraform
#      uses: hashicorp/setup-terraform@v2
#
#    - name: Initialize Terraform
#      run: terraform init ./deployment/aws-infra/
#
#    - name: Apply Terraform
#      run: terraform apply -auto-approve ./deployment/aws-infra/