name: Set OIDC Subject Claim

on:
  workflow_dispatch:

jobs:
  set-oidc-subject-claim:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    - name: Set OIDC subject claim
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/oidc/customization/sub \
          --input ../config/aws-subject.json

    - name: Verify OIDC subject claim
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        export CLAIM_TEMPLATE=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/actions/oidc/customization/sub)
        echo "CLAIM_TEMPLATE=$CLAIM_TEMPLATE" >> "$GITHUB_ENV"

    - name: Status summary
      env:
        CLAIM_TEMPLATE: ${{ env.CLAIM_TEMPLATE }}
      run: |
        echo "## OIDC Subject Claim Template Set" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "$CLAIM_TEMPLATE" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY